//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PerfectButtonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PerfectButton), typeof(UnityEngine.UI.Button));
		L.RegFunction("OnPointerDown", OnPointerDown);
		L.RegFunction("OnPointerUp", OnPointerUp);
		L.RegFunction("OnPointerClick", OnPointerClick);
		L.RegFunction("OnBeginDrag", OnBeginDrag);
		L.RegFunction("OnDrag", OnDrag);
		L.RegFunction("OnEndDrag", OnEndDrag);
		L.RegFunction("AddClickListener", AddClickListener);
		L.RegFunction("ReleaseClickListener", ReleaseClickListener);
		L.RegFunction("AddDoubleClickListener", AddDoubleClickListener);
		L.RegFunction("ReleaseDoubleClickListener", ReleaseDoubleClickListener);
		L.RegFunction("AddDownListener", AddDownListener);
		L.RegFunction("ReleaseDownListener", ReleaseDownListener);
		L.RegFunction("AddUpListener", AddUpListener);
		L.RegFunction("ReleaseUpListener", ReleaseUpListener);
		L.RegFunction("AddLongPressListener", AddLongPressListener);
		L.RegFunction("ReleaseLongPressListener", ReleaseLongPressListener);
		L.RegFunction("AddDragScroll", AddDragScroll);
		L.RegFunction("ReleaseDragScroll", ReleaseDragScroll);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerDown(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerUp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerUp(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBeginDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnBeginDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEndDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnEndDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddClickListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddClickListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseClickListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			obj.ReleaseClickListener();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddDoubleClickListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddDoubleClickListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseDoubleClickListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			obj.ReleaseDoubleClickListener();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddDownListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddDownListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseDownListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			obj.ReleaseDownListener();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddUpListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddUpListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseUpListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			obj.ReleaseUpListener();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddLongPressListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.AddLongPressListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseLongPressListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			obj.ReleaseLongPressListener();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddDragScroll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			UnityEngine.UI.ScrollRect arg0 = (UnityEngine.UI.ScrollRect)ToLua.CheckObject<UnityEngine.UI.ScrollRect>(L, 2);
			obj.AddDragScroll(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseDragScroll(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PerfectButton obj = (PerfectButton)ToLua.CheckObject<PerfectButton>(L, 1);
			obj.ReleaseDragScroll();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

