//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SdkMsgManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SdkMsgManager), typeof(Singleton<SdkMsgManager>));
		L.RegFunction("Init", Init);
		L.RegFunction("LoginQQ", LoginQQ);
		L.RegFunction("New", _CreateSdkMsgManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSdkMsgManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SdkMsgManager obj = new SdkMsgManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SdkMsgManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SdkMsgManager obj = (SdkMsgManager)ToLua.CheckObject<SdkMsgManager>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoginQQ(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SdkMsgManager obj = (SdkMsgManager)ToLua.CheckObject<SdkMsgManager>(L, 1);
			obj.LoginQQ();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

