//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Singleton_SdkMsgManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Singleton<SdkMsgManager>), typeof(System.Object), "Singleton_SdkMsgManager");
		L.RegFunction("New", _CreateSingleton_SdkMsgManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingleton_SdkMsgManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Singleton<SdkMsgManager> obj = new Singleton<SdkMsgManager>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Singleton<SdkMsgManager>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Singleton<SdkMsgManager>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

